//! Top-level convenience builder: render a `DocumentContent` straight
//! to a `.docx` on disk.
//!
//! This is the "third layer" of the pipeline in action — a JSON-ish
//! `DocumentContent` goes in, a fully-styled `.docx` comes out. It
//! composes:
//!
//!   - [`crate::office::docx::renderer`] — block → paragraphs/tables
//!   - [`crate::office::docx::components`] — design-system aware
//!     component builders
//!   - [`crate::office::docx::writer`] — OOXML string assembly
//!   - [`crate::office::docx::zip_writer`] — package the docx
//!
//! Use this from the agent's `create_word_doc` tool, or directly
//! from a CLI / library user that wants the brand visuals without
//! constructing a `WordDocument` by hand.

use crate::office::docx::renderer::{render_document, DocumentContent};
use crate::office::docx::types::{WordDocument, WordParagraph, WordTable};
use crate::office::docx::write_word_document_to_path;
use crate::office::shared::OfficeError;
use std::path::Path;

/// Render `content` and write it to `output_path`. The resulting
/// `.docx` carries every brand style the design system encodes —
///// coloured headings, zebra-striped tables with header repeat,
////// coloured callouts, and shaded code blocks.
///
/// Returns the number of paragraphs / tables / images emitted so
/// callers can log the result.
pub fn write_styled_docx(
    content: &DocumentContent,
    output_path: &Path,
) -> Result<RenderStats, OfficeError> {
    let rendered = render_document(content);
    let stats = RenderStats {
        paragraphs: rendered.paragraphs.len(),
        tables: rendered.tables.len(),
        images: rendered.images.len(),
    };
    let doc = WordDocument {
        paragraphs: rendered.paragraphs,
        tables: rendered.tables,
        images: rendered.images,
        sections: vec![],
        headers: vec![],
        footers: vec![],
    };
    let mut doc = doc;
    // Auto-inject a default section so the writer's fallback sectPr
    // doesn't kick in. The default is A4 portrait with 1-inch margins.
    if doc.sections.is_empty() {
        doc.sections.push(Default::default());
    }
    write_word_document_to_path(&doc, output_path, None)?;
    Ok(stats)
}

/// Statistics about the rendered document — useful for the agent's
/// response payload so it can confirm "I emitted N paragraphs, M
/// tables, K images" without having to re-parse the .docx.
#[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize)]
pub struct RenderStats {
    pub paragraphs: usize,
    pub tables: usize,
    pub images: usize,
}

/// Quick smoke test that writes a single-chapter sample document to
/// `output_path`. Useful for verifying a new environment — the
/// resulting `.docx` is non-trivial (cover, headings, table,
/// callout, code block, lists) and exercises every component.
///
/// Returns the absolute path of the file that was written so the
/// caller can chain another tool (e.g. `smoke_render`) onto it.
pub fn write_sample_document(output_path: &Path) -> Result<std::path::PathBuf, OfficeError> {
    use crate::office::docx::renderer::{CalloutLevelName, ContentBlock};
    let content = DocumentContent {
        title: Some("inkuo Sample Document".to_string()),
        blocks: vec![
            ContentBlock::Cover {
                id: "cover".into(),
                title: "inkuo Brand Document".into(),
                subtitle: Some("A demonstration of the inkuo design system".into()),
            },
            ContentBlock::Chapter {
                id: "ch-intro".into(),
                title: "Introduction".into(),
            },
            ContentBlock::Body {
                id: "p-intro".into(),
                text: Some(
                    "This document is generated by inkuo's Rust document pipeline. \
                     Every paragraph, heading, table, and callout below is rendered \
                     from a structured ContentBlock description into a fully-styled .docx file."
                        .into(),
                ),
                runs: None,
            },
            ContentBlock::Heading {
                id: "h-features".into(),
                level: 2,
                text: "Key Features".into(),
            },
            ContentBlock::BulletList {
                id_prefix: "bl-feat".into(),
                items: vec![
                    "Design-token driven colours and font sizes".into(),
                    "Tables with zebra striping and header-row repeat".into(),
                    "Four flavours of coloured callouts".into(),
                    "Monospace code blocks with shaded backgrounds".into(),
                ],
            },
            ContentBlock::Callout {
                id: "callout-info".into(),
                level: CalloutLevelName::Info,
                title: "How it works".into(),
                body: Some(
                    "Each ContentBlock maps to a component builder that returns the \
                     right paragraphs, runs, and tables. The renderer stitches them \
                     into a WordDocument and the writer emits the OOXML."
                        .into(),
                ),
                body_lines: None,
            },
            ContentBlock::Callout {
                id: "callout-warning".into(),
                level: CalloutLevelName::Warning,
                title: "Heads up".into(),
                body: Some(
                    "Long tables should use the repeat_header option so the header \
                     row appears on every page the table spans."
                        .into(),
                ),
                body_lines: None,
            },
            ContentBlock::Code {
                id: "code-1".into(),
                lines: vec![
                    "use inkuo::office::docx::{render_document, write_styled_docx};".into(),
                    "use inkuo::office::docx::renderer::ContentBlock;".into(),
                    "".into(),
                    "let content = DocumentContent::new(vec![".into(),
                    "    ContentBlock::Body { id: \"p\".into(), text: Some(\"hi\".into()), runs: None },".into(),
                    "]);".into(),
                    "write_styled_docx(&content, \"out.docx\")?;".into(),
                ],
                language: Some("rust".into()),
            },
            ContentBlock::Chapter {
                id: "ch-data".into(),
                title: "Sample Data".into(),
            },
            ContentBlock::Heading {
                id: "h-table".into(),
                level: 2,
                text: "Quarterly Metrics".into(),
            },
            ContentBlock::Table {
                id: "t-metrics".into(),
                headers: vec!["Metric".into(), "Q1".into(), "Q2".into(), "Q3".into(), "Q4".into()],
                rows: vec![
                    vec!["Revenue".into(), "120".into(), "135".into(), "158".into(), "172".into()],
                    vec!["Users".into(), "1.2k".into(), "1.8k".into(), "2.4k".into(), "3.1k".into()],
                    vec!["Retention".into(), "78%".into(), "82%".into(), "85%".into(), "88%".into()],
                ],
                style: None,
            },
            ContentBlock::PageBreak { id: "pb".into() },
            ContentBlock::Heading {
                id: "h-conclusion".into(),
                level: 2,
                text: "Conclusion".into(),
            },
            ContentBlock::Body {
                id: "p-end".into(),
                text: Some(
                    "The inkuo design system produces consistent, professional-looking \
                     documents without requiring the caller to think about colours, \
                     fonts, or spacing. A future enhancement is to plug in a brand \
                     configuration file so each customer can swap palettes without \
                     rebuilding the tool."
                        .into(),
                ),
                runs: None,
            },
        ],
    };
    write_styled_docx(&content, output_path)?;
    Ok(output_path.to_path_buf())
}

#[allow(dead_code)]
fn _unused_anchor(_p: &WordParagraph, _t: &WordTable) {
    let _ = (_p, _t);
}
