// <auto-generated />
using System;
using Inkuso.Cloud.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inkuso.Cloud.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710174422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inkuso.Cloud.Core.Entities.InviteCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FreeQuotaCents")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("InviteCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "INKUO2026",
                            CreatedAt = new DateTime(2026, 7, 10, 17, 44, 22, 89, DateTimeKind.Utc).AddTicks(6451),
                            Enabled = true,
                            FreeQuotaCents = 500m,
                            MaxUses = 9999,
                            UsedCount = 0
                        });
                });

            modelBuilder.Entity("Inkuso.Cloud.Core.Entities.ModelConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("InputPricePer1kTokens")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OutputPricePer1kTokens")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("UpstreamApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpstreamBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpstreamProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ModelConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 10, 17, 44, 22, 89, DateTimeKind.Utc).AddTicks(8105),
                            DisplayName = "DeepSeek-V3",
                            Enabled = true,
                            InputPricePer1kTokens = 0.001m,
                            ModelName = "deepseek-chat",
                            OutputPricePer1kTokens = 0.002m,
                            SortOrder = 1,
                            UpstreamApiKey = "",
                            UpstreamBaseUrl = "https://api.deepseek.com",
                            UpstreamProvider = "deepseek"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 10, 17, 44, 22, 89, DateTimeKind.Utc).AddTicks(9670),
                            DisplayName = "GPT-4o Mini",
                            Enabled = true,
                            InputPricePer1kTokens = 0.00015m,
                            ModelName = "gpt-4o-mini",
                            OutputPricePer1kTokens = 0.0006m,
                            SortOrder = 2,
                            UpstreamApiKey = "",
                            UpstreamBaseUrl = "https://api.openai.com/v1",
                            UpstreamProvider = "openai"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 10, 17, 44, 22, 89, DateTimeKind.Utc).AddTicks(9678),
                            DisplayName = "GPT-4o",
                            Enabled = true,
                            InputPricePer1kTokens = 0.0025m,
                            ModelName = "gpt-4o",
                            OutputPricePer1kTokens = 0.01m,
                            SortOrder = 3,
                            UpstreamApiKey = "",
                            UpstreamBaseUrl = "https://api.openai.com/v1",
                            UpstreamProvider = "openai"
                        });
                });

            modelBuilder.Entity("Inkuso.Cloud.Core.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MonthlyQuotaCents")
                        .HasPrecision(12, 4)
                        .HasColumnType("integer");

                    b.Property<long>("MonthlyTokenLimit")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OverageInputPricePer1k")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)");

                    b.Property<decimal>("OverageOutputPricePer1k")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 10, 17, 44, 22, 88, DateTimeKind.Utc).AddTicks(9885),
                            Enabled = true,
                            MonthlyQuotaCents = 0,
                            MonthlyTokenLimit = 500000L,
                            Name = "Free",
                            OverageInputPricePer1k = 0.002m,
                            OverageOutputPricePer1k = 0.004m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 10, 17, 44, 22, 89, DateTimeKind.Utc).AddTicks(1192),
                            Enabled = true,
                            MonthlyQuotaCents = 2900,
                            MonthlyTokenLimit = 5000000L,
                            Name = "Plus",
                            OverageInputPricePer1k = 0.002m,
                            OverageOutputPricePer1k = 0.004m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 10, 17, 44, 22, 89, DateTimeKind.Utc).AddTicks(1206),
                            Enabled = true,
                            MonthlyQuotaCents = 9900,
                            MonthlyTokenLimit = 25000000L,
                            Name = "Pro",
                            OverageInputPricePer1k = 0.0015m,
                            OverageOutputPricePer1k = 0.003m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 7, 10, 17, 44, 22, 89, DateTimeKind.Utc).AddTicks(1212),
                            Enabled = true,
                            MonthlyQuotaCents = 29900,
                            MonthlyTokenLimit = 100000000L,
                            Name = "Max",
                            OverageInputPricePer1k = 0.001m,
                            OverageOutputPricePer1k = 0.002m
                        });
                });

            modelBuilder.Entity("Inkuso.Cloud.Core.Entities.RedemptionCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditCents")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.ToTable("RedemptionCodes");
                });

            modelBuilder.Entity("Inkuso.Cloud.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Inkuso.Cloud.Core.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Inkuso.Cloud.Core.Entities.UsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CompletionTokens")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CostCents")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)");

                    b.Property<Guid>("ModelConfigId")
                        .HasColumnType("uuid");

                    b.Property<long>("PromptTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestId")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModelConfigId");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("UsageRecords");
                });

            modelBuilder.Entity("Inkuso.Cloud.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BalanceCents")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InviteCodeUsed")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Inkuso.Cloud.Core.Entities.RedemptionCode", b =>
                {
                    b.HasOne("Inkuso.Cloud.Core.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Inkuso.Cloud.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("Inkuso.Cloud.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Inkuso.Cloud.Core.Entities.Subscription", b =>
                {
                    b.HasOne("Inkuso.Cloud.Core.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inkuso.Cloud.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Inkuso.Cloud.Core.Entities.UsageRecord", b =>
                {
                    b.HasOne("Inkuso.Cloud.Core.Entities.ModelConfig", "ModelConfig")
                        .WithMany()
                        .HasForeignKey("ModelConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inkuso.Cloud.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelConfig");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
