// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileEntry = { name: string, path: string, is_dir: boolean, 
/**
 * Coarse-grained classification driving the editor + icon mapping.
 * Possible values: `word`, `excel`, `image`, `pdf`, `code`, `config`,
 * `data`, `markdown`, `text`, `binary`, `audio`, `video`, `archive`.
 * The frontend keeps `is_markdown` for backwards compatibility — it is
 * `true` iff `file_kind == "markdown" || file_kind == "text"`.
 */
file_kind: string, 
/**
 * Kept for backwards compatibility — true if the file is a markdown
 * document. Prefer `file_kind`.
 */
is_markdown: boolean, };
